kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-gp3-pvc
  namespace: team1-tenant1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem

